image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-f ./sigeh"

cache:
  paths:
    - .m2/repository

construir:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - sigeh/target/

 
testar integrado:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -Dtest=br.com.sigeh.test.BOIntegrationTest org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile surefire:test 

testar unitario:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -Dtest=br.com.sigeh.test.BOTest org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile surefire:test

implantar:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar deploy:deploy
  only:
    - tags
